// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grpc/user-service/user-service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginSpotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        *string                `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSpotifyRequest) Reset() {
	*x = LoginSpotifyRequest{}
	mi := &file_grpc_user_service_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSpotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSpotifyRequest) ProtoMessage() {}

func (x *LoginSpotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSpotifyRequest.ProtoReflect.Descriptor instead.
func (*LoginSpotifyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginSpotifyRequest) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

type LoginSpotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSpotifyResponse) Reset() {
	*x = LoginSpotifyResponse{}
	mi := &file_grpc_user_service_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSpotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSpotifyResponse) ProtoMessage() {}

func (x *LoginSpotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSpotifyResponse.ProtoReflect.Descriptor instead.
func (*LoginSpotifyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginSpotifyResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type SpotifyCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *string                `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	Code          *string                `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotifyCallbackRequest) Reset() {
	*x = SpotifyCallbackRequest{}
	mi := &file_grpc_user_service_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotifyCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyCallbackRequest) ProtoMessage() {}

func (x *SpotifyCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_user_service_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyCallbackRequest.ProtoReflect.Descriptor instead.
func (*SpotifyCallbackRequest) Descriptor() ([]byte, []int) {
	return file_grpc_user_service_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *SpotifyCallbackRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *SpotifyCallbackRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

var File_grpc_user_service_user_service_proto protoreflect.FileDescriptor

const file_grpc_user_service_user_service_proto_rawDesc = "" +
	"\n" +
	"$grpc/user-service/user-service.proto\x12\x13lovify_user_service\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x13LoginSpotifyRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"(\n" +
	"\x14LoginSpotifyResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"B\n" +
	"\x16SpotifyCallbackRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code2\xca\x01\n" +
	"\vUserService\x12c\n" +
	"\fLoginSpotify\x12(.lovify_user_service.LoginSpotifyRequest\x1a).lovify_user_service.LoginSpotifyResponse\x12V\n" +
	"\x0fSpotifyCallback\x12+.lovify_user_service.SpotifyCallbackRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13lovify-user/serviceb\beditionsp\xe8\a"

var (
	file_grpc_user_service_user_service_proto_rawDescOnce sync.Once
	file_grpc_user_service_user_service_proto_rawDescData []byte
)

func file_grpc_user_service_user_service_proto_rawDescGZIP() []byte {
	file_grpc_user_service_user_service_proto_rawDescOnce.Do(func() {
		file_grpc_user_service_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_user_service_user_service_proto_rawDesc), len(file_grpc_user_service_user_service_proto_rawDesc)))
	})
	return file_grpc_user_service_user_service_proto_rawDescData
}

var file_grpc_user_service_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_user_service_user_service_proto_goTypes = []any{
	(*LoginSpotifyRequest)(nil),    // 0: lovify_user_service.LoginSpotifyRequest
	(*LoginSpotifyResponse)(nil),   // 1: lovify_user_service.LoginSpotifyResponse
	(*SpotifyCallbackRequest)(nil), // 2: lovify_user_service.SpotifyCallbackRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_grpc_user_service_user_service_proto_depIdxs = []int32{
	0, // 0: lovify_user_service.UserService.LoginSpotify:input_type -> lovify_user_service.LoginSpotifyRequest
	2, // 1: lovify_user_service.UserService.SpotifyCallback:input_type -> lovify_user_service.SpotifyCallbackRequest
	1, // 2: lovify_user_service.UserService.LoginSpotify:output_type -> lovify_user_service.LoginSpotifyResponse
	3, // 3: lovify_user_service.UserService.SpotifyCallback:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_user_service_user_service_proto_init() }
func file_grpc_user_service_user_service_proto_init() {
	if File_grpc_user_service_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_user_service_user_service_proto_rawDesc), len(file_grpc_user_service_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_user_service_user_service_proto_goTypes,
		DependencyIndexes: file_grpc_user_service_user_service_proto_depIdxs,
		MessageInfos:      file_grpc_user_service_user_service_proto_msgTypes,
	}.Build()
	File_grpc_user_service_user_service_proto = out.File
	file_grpc_user_service_user_service_proto_goTypes = nil
	file_grpc_user_service_user_service_proto_depIdxs = nil
}
